### ISSUE TITLE
[Question] mutate node elements

### ISSUE THREAD

**Issue by zen3ger** [RazrFalcon/libsvgdom#9]
Is it possible to mutate specific node elements in the dom?
I would like to emulate svg scripting and (for now) just change the color of some rectangles.

**Comment by RazrFalcon** [comment]
Something like this:
```rust
extern crate svgdom;

fn main() {
    let doc = svgdom::Document::from_str("<svg><rect/></svg>").unwrap();

    let mut rect_node = doc.first_child().unwrap().first_child().unwrap();
    rect_node.set_attribute((svgdom::AttributeId::Fill, svgdom::Color::new(255, 0, 0)));

    println!("{}", doc);
}
```
?

**Comment by zen3ger** [comment]
Yes, thank you!
And if I were to look for a node in the document I should use the `Document::descendants()` to do the `doc.first_child().unwrap().first_child().unwrap()` part, right?
